In [1]:
#FINALMENTE DEL CODICEEEEH

In [2]:
import numpy as np
#
import tensorflow as tf
from tensorflow.keras.backend import clear_session
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer,Dense

In [3]:
#say no to warnings!
import warnings
warnings.filterwarnings("ignore")
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
import tensorflow as tf
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

# MODELLO SEQUENZIALE

In [4]:
seq_model = Sequential()
input_layer = InputLayer(input_shape=(100,))
hidden_layer_one = Dense(128,activation='relu')
hidden_layer_two = Dense(32,activation='relu')
output_layer = Dense(10,activation='softmax')

In [5]:
seq_model.add(input_layer)
seq_model.add(hidden_layer_one)
seq_model.add(hidden_layer_two)
seq_model.add(output_layer)

In [6]:
seq_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               12928     
_________________________________________________________________
dense_1 (Dense)              (None, 32)                4128      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                330       
Total params: 17,386
Trainable params: 17,386
Non-trainable params: 0
_________________________________________________________________


In [7]:
print((100+1)*128)
print((128+1)*32)
print((32+1)*10)

12928
4128
330


In [8]:
def get_seq_model():
    seq_model = Sequential()
    input_layer = InputLayer(input_shape=(100,))
    hidden_layer_one = Dense(128,activation='relu')
    hidden_layer_two = Dense(32,activation='relu')
    output_layer = Dense(10,activation='softmax')
    seq_model.add(input_layer)
    seq_model.add(hidden_layer_one)
    seq_model.add(hidden_layer_two)
    seq_model.add(output_layer)
    return seq_model

# Propagazione in avanti

In [9]:
x = np.random.rand(1,100).astype(np.float32)

In [10]:
seq_model = get_seq_model()
seq_model.predict(x)

array([[0.0888828 , 0.11633698, 0.18995553, 0.1260561 , 0.08493721,
        0.08098055, 0.04852037, 0.10522322, 0.07181891, 0.08728833]],
      dtype=float32)

In [11]:
seq_model.predict(x)

array([[0.0888828 , 0.11633698, 0.18995553, 0.1260561 , 0.08493721,
        0.08098055, 0.04852037, 0.10522322, 0.07181891, 0.08728833]],
      dtype=float32)

In [12]:
seq_model = get_seq_model()
seq_model.predict(x)

array([[0.1506617 , 0.08956368, 0.08078044, 0.08538312, 0.09062907,
        0.09775218, 0.11739088, 0.11615082, 0.08353748, 0.08815066]],
      dtype=float32)

In [13]:
for _ in range(10):
    seq_model = get_seq_model()
    pred = seq_model.predict(x)
    print(sum(pred[0]))

1.000000037252903
0.9999999441206455
1.000000063329935
0.9999999441206455
0.9999999962747097
0.9999999552965164
0.9999999701976776
0.9999999664723873
0.9999999478459358
0.9999999552965164


In [14]:
x = np.random.rand(1,100).astype(np.float32)
seq_model.predict(x).shape

(1, 10)

In [15]:
x = np.random.rand(42,100).astype(np.float32)
seq_model.predict(x).shape

(42, 10)

# Pulizia backend

In [16]:
seq_model = get_seq_model()
seq_model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_39 (Dense)             (None, 128)               12928     
_________________________________________________________________
dense_40 (Dense)             (None, 32)                4128      
_________________________________________________________________
dense_41 (Dense)             (None, 10)                330       
Total params: 17,386
Trainable params: 17,386
Non-trainable params: 0
_________________________________________________________________


In [17]:
seq_model = get_seq_model()
seq_model.summary()

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_42 (Dense)             (None, 128)               12928     
_________________________________________________________________
dense_43 (Dense)             (None, 32)                4128      
_________________________________________________________________
dense_44 (Dense)             (None, 10)                330       
Total params: 17,386
Trainable params: 17,386
Non-trainable params: 0
_________________________________________________________________


In [18]:
clear_session()
seq_model = get_seq_model()
seq_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               12928     
_________________________________________________________________
dense_1 (Dense)              (None, 32)                4128      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                330       
Total params: 17,386
Trainable params: 17,386
Non-trainable params: 0
_________________________________________________________________


# Funzioni di attivazione

In [19]:
def get_seq_model(myfun):
    seq_model = Sequential()
    input_layer = InputLayer(input_shape=(100,))
    hidden_layer_one = Dense(128,activation='relu')
    hidden_layer_two = Dense(32,activation='relu')
    output_layer = Dense(10,activation=myfun)
    seq_model.add(input_layer)
    seq_model.add(hidden_layer_one)
    seq_model.add(hidden_layer_two)
    seq_model.add(output_layer)
    return seq_model

In [20]:
model = get_seq_model('softmax')
pred = model.predict(np.random.rand(1,100))
print(pred)
print('shape',pred.shape)
print('sum',sum(pred[0]))

[[0.14652473 0.10605922 0.07214168 0.05889107 0.21365462 0.09596379
  0.04705328 0.05335679 0.03839457 0.16796027]]
shape (1, 10)
sum 1.0000000223517418


In [21]:
model = get_seq_model('linear')
pred = model.predict(np.random.rand(1,100))
print(pred)
print('shape',pred.shape)
print('sum',sum(pred[0]))

[[-0.8758651   0.0408582  -0.05814026  0.00749208 -0.5384035   0.84914935
   0.10018453 -0.5832264   0.16045608 -0.00771484]]
shape (1, 10)
sum -0.9052098579704762


In [22]:
model = get_seq_model('sigmoid')
pred = model.predict(np.random.rand(1,100))
print(pred)
print('shape',pred.shape)
print('sum',sum(pred[0]))

[[0.52772576 0.5658507  0.5517045  0.63573855 0.513419   0.52008706
  0.55238587 0.44009358 0.6875631  0.516129  ]]
shape (1, 10)
sum 5.51069712638855


# Funzione di attivazione custom

In [23]:
def f(x):
    return x*10000
model = get_seq_model(f)
pred = model.predict(np.random.rand(1,100))
print(pred)
print('shape',pred.shape)
print('sum',sum(pred[0]))

[[  675.4378   2355.281    5073.9897   2437.4138   -441.79822  1740.3484
   1278.4542   1595.2198  -1814.5879   3289.828  ]]
shape (1, 10)
sum 16189.586608886719


In [24]:
f = lambda x:x*10000
model = get_seq_model(f)
pred = model.predict(np.random.rand(1,100))
print(pred)
print('shape',pred.shape)
print('sum',sum(pred[0]))

[[-3009.186   -2041.771    -568.60913  6148.2847   -490.44083 -1408.1832
  -2511.015    5008.2637    866.76965  2256.4666 ]]
shape (1, 10)
sum 4250.579437255859
